### ISSUE TITLE
Crash with ME Bridge

### ISSUE THREAD

**Issue by DerMistkaefer** [austinv11/PeripheralsPlusPlus#140]
When I place the ME Bridge my Game is crashing.

Mods:
Forge: 10.13.4.1558
appliedenergistics2-rv3-beta-3
CollectiveFramework-1.0.0-132
ComputerCraft1.75
Peripherals++-1.3.3

Crash Report:
```
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 1/5/16 10:15 PM
Description: Ticking block entity

java.lang.NoClassDefFoundError: appeng/core/WorldSettings
	at com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge.func_145845_h(TileEntityMEBridge.java:78)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: appeng.core.WorldSettings
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge.func_145845_h(TileEntityMEBridge.java:78)

-- Block entity being ticked --
Details:
	Name: meBridge // com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge
	Block type: ID #409 (tile.peripheralsplusplus:meBridge // com.austinv11.peripheralsplusplus.blocks.BlockMEBridge)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (576,4,1614), Chunk: (at 0,0,14 in 36,100; contains blocks 576,0,1600 to 591,255,1615), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
	Actual block type: ID #409 (tile.peripheralsplusplus:meBridge // com.austinv11.peripheralsplusplus.blocks.BlockMEBridge)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: test
	All players: 1 total; [EntityPlayerMP['DerMistkaefer'/0, l='test', x=576.50, y=4.00, z=1611.50]]
	Chunk stats: ServerChunkCache: 1414 Drop: 0
	Level seed: 4333147455264049845
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (586,4,1607), Chunk: (at 10,0,7 in 36,100; contains blocks 576,0,1600 to 591,255,1615), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
	Level time: 420 game time, 420 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 14985 (now: false), thunder time: 67248 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_66, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1217095008 bytes (1160 MB) / 1635778560 bytes (1560 MB) up to 7635730432 bytes (7282 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx8192m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	CollectiveFrameworkCore{1.0.0-132} [Collective Framework Core] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-3} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	PeripheralsPlusPlusCore{1.3.3} [Peripherals++ Core] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-3} [Applied Energistics 2] (appliedenergistics2-rv3-beta-3.jar) 
	UCHIJAAAA	CollectiveFramework{1.0.0-132} [Collective Framework] (CollectiveFramework-1.0.0-132.jar) 
	UCHIJAAAA	ComputerCraft{1.75} [ComputerCraft] (ComputerCraft1.75.jar) 
	UCHIJAAAA	PeripheralsPlusPlus{1.3.3} [Peripherals++] (Peripherals++-1.3.3.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: beta rv3-beta-3 for Forge 10.13.4.1448
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:OFF, InvTweaks:OFF, NEI:OFF, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['DerMistkaefer'/0, l='test', x=576.50, y=4.00, z=1611.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
```

I hope I can help you.

**Comment by SquidDev** [comment]
@austinv11 WorldSettings has moved to [WorldData](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/core/worlddata/WorldData.java).

**Comment by grandmind** [comment]
Unfortunately, it's impractical to try to support beta versions of mods. Please revert Applied Energistics to a stable version.

**Comment by DerMistkaefer** [comment]
But ehe last stable build was at 6.7.2015 and I will have new features.

**Comment by grandmind** [comment]
Here, this should fix the crash. 
https://file.io/BwLZIk
