### ISSUE TITLE
MEBridge crash 

### ISSUE THREAD

**Issue by norfair** [austinv11/PeripheralsPlusPlus#34]
MEBridge crash in ae2RV2

**Comment by grandmind** [comment]
I need a crash log in order to help you.

**Comment by austinv11** [comment]
http://vazkii.us/br101/

**Comment by norfair** [comment]
```
java.lang.AbstractMethodError: com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge.isWorldAccessible()Z
	at appeng.me.GridNode.FindConnections(GridNode.java:354)
	at appeng.me.GridNode.updateState(GridNode.java:207)
	at com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge.func_145845_h(TileEntityMEBridge.java:79)
	at net.minecraft.world.World.func_72939_s(World.java:1939)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

**Comment by austinv11** [comment]
I'm gonna need more details, what did you do to cause the crash?

**Comment by Selim042** [comment]
I had the same problem, I placed the ME Bridge, then it froze for a second, and crashed.

**Comment by austinv11** [comment]
Okay, the issue is with ae2. If you can't access your world, I suggest downgrading ae2 to rv1. I'll have to look into updating it to the latest api.

**Comment by Selim042** [comment]
Umm, still doesn't work for me, I have AE2 RV2, Beta 8, and Peripherals++ 1.2.1.
http://pastebin.com/LQEBMBKc

**Comment by grandmind** [comment]
You're aware that you didn't actually update Peripherals++ to the version where the bug is fixed, yes? The bug isn't magically fixed for you on and old version.
