### ISSUE TITLE
crash on installing mods (mebrige) dont have ae2

### ISSUE THREAD

**Issue by monkeybee11** [austinv11/PeripheralsPlusPlus#69]
hai with this mod in stalled im crashing on modinstaling the strange thing is that im not evenusing AE 

---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 02/06/15 15:40
Description: Initializing game

java.lang.NoClassDefFoundError: com/austinv11/peripheralsplusplus/tiles/TileEntityMEBridge
	at com.austinv11.peripheralsplusplus.init.ModBlocks.<clinit>(ModBlocks.java:25)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:532)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.austinv11.peripheralsplusplus.tiles.TileEntityMEBridge
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 16 more
Caused by: java.lang.NoClassDefFoundError: appeng/api/networking/security/IActionHost
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 18 more
Caused by: java.lang.ClassNotFoundException: appeng.api.networking.security.IActionHost
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 24 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.austinv11.peripheralsplusplus.init.ModBlocks.<clinit>(ModBlocks.java:25)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.scanTarget(ObjectHolderRegistry.java:70)
	at cpw.mods.fml.common.registry.ObjectHolderRegistry.findObjectHolders(ObjectHolderRegistry.java:39)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:532)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:241)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 105347904 bytes (100 MB) / 290525184 bytes (277 MB) up to 1060372480 bytes (1011 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.140.1401 Minecraft Forge 10.13.3.1401 7 mods loaded, 7 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed
	FML{7.10.140.1401} [Forge Mod Loader] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed
	Forge{10.13.3.1401} [Minecraft Forge] (forge-1.7.10-10.13.3.1401-1710ls.jar) Unloaded->Constructed
	OpenComputers|Core{1.0.0} [OpenComputers (Core)] (minecraft.jar) Unloaded->Constructed
	ComputerCraft{1.73} [ComputerCraft] (ComputerCraft1.73.jar) Unloaded->Constructed
	OpenComputers{1.5.12.26} [OpenComputers] (OpenComputers-MC1.7.10-1.5.12.26-universal.jar) Unloaded->Constructed
	PeripheralsPlusPlus{1.2.9} [Peripherals++] (Peripherals++-1.2.9.jar) Unloaded->Constructed
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.2.12422 Compatibility Profile Context 13.152.0.0' Renderer: 'AMD Radeon HD 8550G'
	Launched Version: 1.7.10-Forge10.13.3.1401-1710ls
	LWJGL: 2.9.1
	OpenGL: AMD Radeon HD 8550G GL version 4.2.12422 Compatibility Profile Context 13.152.0.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [pizza]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by MFernflower** [comment]
Delete your configs and update to the newest release of this mod. It fixed my client!

**Comment by austinv11** [comment]
Like @MFernflower said, update Peripherals++
