### ISSUE TITLE
crash-reports

### ISSUE THREAD

**Issue by WhileBr** [austinv11/PeripheralsPlusPlus#99]
---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 30/07/15 10:25
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: dan200/computercraft/shared/pocket/items/ItemPocketComputer
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:544)
	at cpw.mods.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:208)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:480)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/shared/pocket/items/ItemPocketComputer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at cpw.mods.fml.common.ProxyInjector.inject(ProxyInjector.java:59)
	at cpw.mods.fml.common.FMLModContainer.constructMod(FMLModContainer.java:512)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.loadMods(Loader.java:513)
	... 10 more
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.shared.pocket.items.ItemPocketComputer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 36 more
Caused by: java.lang.NoClassDefFoundError: com/austinv11/collectiveframework/minecraft/config/ConfigException
	at com.austinv11.peripheralsplusplus.asm.Transformer.transform(Transformer.java:17)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 38 more
Caused by: java.lang.ClassNotFoundException: com.austinv11.collectiveframework.minecraft.config.ConfigException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 130291792 bytes (124 MB) / 378089472 bytes (360 MB) up to 2134114304 bytes (2035 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_C1 72 mods loaded, 72 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UC	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UC	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UC	Mocap-core{1.0} [Motion Capture (Core)] (minecraft.jar) 
	UC	NotEnoughItems{1.0.5.111} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
	UC	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UC	PeripheralsPlusPlusCore{1.3.1} [Peripherals++ Core] (minecraft.jar) 
	UC	adventurebackpack{1.7.10-0.8b} [Adventure Backpack] (adventurebackpack-1.7.10-0.8b.jar) 
	UC	BiblioCraft{1.10.5} [BiblioCraft] (BiblioCraft[v1.10.5][MC1.7.10].jar) 
	UC	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UC	BuildCraft|Core{7.0.17} [BuildCraft] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Factory{7.0.17} [BC Factory] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Energy{7.0.17} [BC Energy] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Silicon{7.0.17} [BC Silicon] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Builders{7.0.17} [BC Builders] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Robotics{7.0.17} [BC Robotics] (buildcraft-7.0.17.jar) 
	UC	BuildCraft|Transport{7.0.17} [BC Transport] (buildcraft-7.0.17.jar) 
	UC	Railcraft{9.6.1.0} [Railcraft] (Railcraft_1.7.10-9.6.1.0.jar) 
	UC	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	chisel{2.4.1.40} [Chisel 2] (Chisel2-2.4.1.40.jar) 
	UC	ctmlib{1.0.1.5} [CTMLib] (Chisel2-2.4.1.40.jar) 
	UE	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UE	chunkyperipherals{1.1.2.0} [Chunky Peripherals] (chunkyperipherals-1.7.10-1.1.2.0.jar) 
	UC	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UC	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UC	Eln{50} [Electrical Age] (ElectricalAge_BETA-1.10_r50.jar) 
	UC	EnderStorage{1.4.7.36} [EnderStorage] (EnderStorage-1.7.10-1.4.7.36-universal.jar) 
	UC	GalacticraftCore{3.0.11} [Galacticraft Core] (GalacticraftCore-1.7-3.0.11.333.jar) 
	UC	GalacticraftMars{3.0.11} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.11.333.jar) 
	UC	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UC	inventorytweaks{1.58-147-645ca10} [Inventory Tweaks] (InventoryTweaks-1.58-147.jar) 
	UC	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UC	ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.0-102.jar) 
	UC	ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
	UC	LogisticsPipes{0.9.2.19} [Logistics Pipes] (logisticspipes-0.9.2.19.jar) 
	UC	Mekanism{8.1.7} [Mekanism] (Mekanism-1.7.10-8.1.7.252.jar) 
	UC	MekanismGenerators{8.1.7} [MekanismGenerators] (MekanismGenerators-1.7.10-8.1.7.252.jar) 
	UC	MekanismTools{8.1.7} [MekanismTools] (MekanismTools-1.7.10-8.1.7.252.jar) 
	UC	Mocap{1.0} [Motion Capture] (Mocap-1.0-(1.7.10).jar) 
	UC	neiintegration{1.0.11} [NEI Integration] (NEIIntegration-MC1.7.10-1.0.11.jar) 
	UE	PeripheralsPlusPlus{1.3.1} [Peripherals++] (Peripherals++-1.3.1.jar) 
	UC	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
	UC	MrTJPCoreMod{1.1.0.30} [MrTJPCore] (MrTJPCore-1.1.0.30-universal.jar) 
	UC	ProjRed|Core{4.7.0pre7.91} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre7.91-Base.jar) 
	UC	ProjRed|Transmission{4.7.0pre7.91} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
	UC	ProjRed|Transportation{4.7.0pre7.91} [ProjectRed Transportation] (ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
	UC	ProjRed|Exploration{4.7.0pre7.91} [ProjectRed Exploration] (ProjectRed-1.7.10-4.7.0pre7.91-World.jar) 
	UC	ProjRed|Compatibility{4.7.0pre7.91} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre7.91-Compat.jar) 
	UC	ProjRed|Integration{4.7.0pre7.91} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
	UC	ProjRed|Fabrication{4.7.0pre7.91} [ProjectRed Fabrication] (ProjectRed-1.7.10-4.7.0pre7.91-Fabrication.jar) 
	UC	ProjRed|Illumination{4.7.0pre7.91} [ProjectRed Illumination] (ProjectRed-1.7.10-4.7.0pre7.91-Lighting.jar) 
	UC	ProjRed|Expansion{4.7.0pre7.91} [ProjectRed Expansion] (ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
	UC	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UC	RopesPlus{1.6.4} [Ropes+] (RopePlus-1.7.10.jar) 
	UC	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UC	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UC	YALSM{2.1.3} [Yet Another Leather Smelting Mod] (yalsm-2.1.3.jar) 
	UC	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UC	ForgeRelocation{0.0.1.3} [ForgeRelocation] (ForgeRelocation-0.0.1.3-universal.jar) 
	UC	MCFrames{1.0} [MCFrames] (ForgeRelocation-0.0.1.3-universal.jar) 
	UC	RelocationFMP{0.0.1.2} [RelocationFMP] (ForgeRelocationFMP-0.0.1.2-universal.jar) 
	UC	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 347.52' Renderer: 'GeForce GTX 650/PCIe/SSE2'
	CoFHCore: -[1.7.10]3.0.3-303
	ThermalFoundation: -[1.7.10]1.2.0-102
	ThermalExpansion: -[1.7.10]4.0.3B1-218

**Comment by WhileBr** [comment]
por favor resolva este crash-reports por que gosto muito deste mod

**Comment by SquidDev** [comment]
It looks like you're missing [Collective Framework](http://minecraft.curseforge.com/mc-mods/232966-collective-framework). It is now [required](http://www.computercraft.info/forums2/index.php?/topic/20903-mc-1710cc-165-173-peripherals-v130-miscperipherals-reimagined-includes-speakers-and-pocket-computer-upgrades/page__pid__227471__st__140#entry227471).
